[project]
name = "AutoBangumi"
version = "1.2.2"
description = "AutoBangumi 是基于 RSS 的全自动追番整理下载工具。只需要在 Mikan Project 等网站上订阅番剧，就可以全自动追番。 并且整理完成的名称和目录可以直接被 Plex、Jellyfin 等媒体库软件识别，无需二次刮削。"
dependencies = [
    "sqlmodel>=0.0.21",
    "torrentool>=1.2.0",
    "pydantic>=2.8.2",
    "httpx[socks,http2]>=0.27.0",
    "lxml>=5.2.2",
    "openai>=1.37.0",
    "python-dotenv>=1.0.1",
    "python-jose>=3.3.0",
    "qbittorrent-api>=2024.7.64",
    "bs4>=0.0.2",
    "semver>=3.0.2",
    "sse-starlette>=2.1.2",
    "passlib[bcrypt]>=1.7.4",
    "bcrypt==4.0.1",
    "fastapi-slim>=0.111.1",
    "uvicorn>=0.30.3",
    "python-multipart>=0.0.9",
    "jinja2>=3.1.4",
    "loguru>=0.7.2",
]
requires-python = ">=3.14"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = false

[dependency-groups]
dev = [
    "ruff>=0.5.4",
    "black>=24.4.2",
    "pre-commit>=3.7.1",
    "pytest>=8.3.1",
    "basedpyright>=1.39.9",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/module"]

[tool.ruff]
target-version = "py314"

[tool.ruff.lint]
ignore = [
    # E501: https://beta.ruff.rs/docs/rules/line-too-long/
    'E501',
    # F401: https://beta.ruff.rs/docs/rules/unused-import/
    # avoid unused imports lint in `__init__.py`
    # 'F401',
]

select = [
    "E",      # pycodestyle errors
    "W",      # pycodestyle warnings
    "F",      # pyflakes
    "I",      # isort
    "B",      # flake8-bugbear
    "C4",     # flake8-comprehensions
    "UP",     # pyupgrade
    "ARG001", # unused arguments in functions
]
